# Generated by Django 6.0.7 on 2026-07-24 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='village', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='village.village')),
            ],
            options={
                'unique_together': {('village', 'type')},
            },
        ),
        migrations.CreateModel(
            name='BuildingSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=32)),
                ('grid_x', models.PositiveIntegerField()),
                ('grid_y', models.PositiveIntegerField()),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='village.village')),
            ],
            options={
                'unique_together': {('village', 'grid_x', 'grid_y')},
            },
        ),
    ]
